# Python Tutorial

In [3]:
print('Hello, BitTiger students!')

Hello, BitTiger students!


### If you want to roughly learn Python, the followings are the most important things you have to know:
### Data Structures: 1. List, 2. Dictionary, 3. numpy.array, 4. pandas.DataFrame
### Container: 索引，添删，排序，切片。。。其中的内容不需要死记硬背，在coding中可以按照需求google，再熟练运用起来。

# 1. Data Type

### string 字符串
#### 单引号：
#### 双引号：
#### 三引号：

In [4]:
decription1 = 'We are now learning DL from BitTiger.'
decription2 = "We are now learning 'DL' from BitTiger."
decription2 = "We are now learning 'DL'. \
It is from BitTiger."
decription3 = '''We are now learning "DL".
It is from BitTiger.'''

print(decription1)
print(decription2)
print(decription3)

We are now learning DL from BitTiger.
We are now learning 'DL'. It is from BitTiger.
We are now learning "DL".
It is from BitTiger.


### number 数字类型
#### int，整形：
#### float，浮点型：
#### 自动推导：

In [5]:
a = 1
type(a)

a = 1.0
type(a)

a = 1.0 / 1
type(a)

a = 1 / 1.0
type(a)

float

# 2. Calculations

### 加减乘除和位运算

In [6]:
# Normal calculations 普通运算
a = 1 + 2
print('a =', a)
b = 1 / 2
print('b =', b)
c = 2 ** 5
print('c =', c)
d = 10 % 3
print('d =', d)

# Bit manipulation 位运算
e = 1 << 3
print('e =', e)
e = 1 >> 1
print('e =', e)
f = 15 & 0
print('f =', f)
f = 15 | 0
print('f =', f)
f = 15 ^ 0
print('f =', f)
f = ~15
print('f =', f)


('a =', 3)
('b =', 0)
('c =', 32)
('d =', 1)
('e =', 8)
('e =', 0)
('f =', 0)
('f =', 15)
('f =', 15)
('f =', -16)


In [7]:
# logic 逻辑运算
a = True and False
print('a =', a)
b = True or False
print('b =', b)
c = 1 == 2
print('c =', c)
d = not True
print d

('a =', False)
('b =', True)
('c =', False)
False


# 3. Data Structures

In [8]:
# List 列表 ！！！ 如果没有时间完全学习python，这里重点看
# 序列 sequential
studentList = ['Lily', 'Lucy', 'Polly', 'Lin Tao', 'Tom']
studentList2 = [1, 1.5, 'Lucy']
print('We have', len(studentList), 'students in our class.')
print()

# 遍历
for student in studentList:
    print(student)
print ""
   
# 元素操作
studentList[1] = 'Lucia'    
print(studentList)
print()
    
# 末尾插入  
# sequential 
# studentList.insert()
studentList.append('Uncle Wong')
print('Today we have a new student Uncle Wong!')
print('So the list is now:', studentList)
print()

# 删除
del studentList[0]
print('List after deleting:', studentList)
print()

# 排序


print('Sorted list:', studentList.sort())
print()



# 切片
print('The following are segmentation results:')
print(studentList[:])
print(studentList[0:2])
print(studentList[-2:])
print(studentList[-2:-1])
print(studentList[0:4:2]) # 0 and 2
print(studentList[:-1])
print()

# 常用初始化
print('Other initialization:')
# list comprehension
list1 = [1 for n in range(1, 101)]
print(list1)

list2 = [n for n in range(1, 101, 2)]
print(list2)

list3 = [1] * 100
print(list3)
# 合并
list4 = list1 + list2
print(list4)
print()


# 最大值
print('Max and min:')
print(max(list4))
print(min(list4))

# 其他函数： count remove insert pop reverse sort等等
list4.reverse()
print(list4)

('We have', 5, 'students in our class.')
()
Lily
Lucy
Polly
Lin Tao
Tom

['Lily', 'Lucia', 'Polly', 'Lin Tao', 'Tom']
()
Today we have a new student Uncle Wong!
('So the list is now:', ['Lily', 'Lucia', 'Polly', 'Lin Tao', 'Tom', 'Uncle Wong'])
()
('List after deleting:', ['Lucia', 'Polly', 'Lin Tao', 'Tom', 'Uncle Wong'])
()
('Sorted list:', None)
()
The following are segmentation results:
['Lin Tao', 'Lucia', 'Polly', 'Tom', 'Uncle Wong']
['Lin Tao', 'Lucia']
['Tom', 'Uncle Wong']
['Tom']
['Lin Tao', 'Polly']
['Lin Tao', 'Lucia', 'Polly', 'Tom']
()
Other initialization:
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 

In [9]:
# Tuple 元组
studentList = ('Lily', 'Lucy', 'Polly', 'Lin Tao', 'Tom')
print('We have', len(studentList), 'students in our class.')
for iter in studentList:
    print(iter)


('We have', 5, 'students in our class.')
Lily
Lucy
Polly
Lin Tao
Tom


In [10]:
# Dictionary 字典 ！！！ 如果没有时间完全学习python，这里重点看
# 哈希表!!!!!
studentTest = {'Lily': 99, 'Lucy': 90, 'Polly': 20, 'Lin Tao': 60, 'Tom': 99}
print('We have', len(studentList), 'students in our class.')

# 遍历
for studentName in studentTest:
    print(studentName)

print('Test result:')
for k, v in studentTest.items():
    print(k, v)
print ""

# dictionary.items() output a list of tuple(k,v)

# 元素
print('Lily:', studentTest['Lily'])

# 赋值
studentTest['Polly'] = 80
print(studentTest)

# studentTest['Tom'] # will give an error
# 
s = 'Tom' 
if s in studentTest:
    print(studentTest[s])



('We have', 5, 'students in our class.')
Polly
Lin Tao
Lily
Lucy
Tom
Test result:
('Polly', 20)
('Lin Tao', 60)
('Lily', 99)
('Lucy', 90)
('Tom', 99)

('Lily:', 99)
{'Polly': 80, 'Lin Tao': 60, 'Lily': 99, 'Lucy': 90, 'Tom': 99}
99


# 4. If, while, for

In [11]:
student1 = 'Lin Tao'
if student1:
    print('Student1 is not NULL')
    
for i in range(0, 101):
    print(i)

i = 0
while(i < 101):
    print(i)
    i += 1

Student1 is not NULL
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


# 5. Numpy

In [12]:
import numpy as np

# If you used to be a Matlab user, refer to the following site:
# https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

# initialization and attributes
a = np.array([1, 2, 3, 4])
print(a)
print(a.shape)
print(a.ndim)

b = np.array([[1], [2], [3], [4]])
print(b)
print(b.shape)
print(b.ndim)
print(type(b))
print()

print(b.size)

[1 2 3 4]
(4,)
1
[[1]
 [2]
 [3]
 [4]]
(4, 1)
2
<type 'numpy.ndarray'>
()
4


In [13]:
# initialization
print(np.array([5, 6, 7, 8]))
print ""

print(np.array([[1, 2],[3, 4]]))
print ""

print(np.arange(51)) # similar to range
print ""

print(np.arange(51).reshape(3,17)) 
# pay attention to the difference between numpy array and python list
print ""

print(np.linspace(1,3,9)) # from 1 to 3, evenly pick 9 numbers
print ""

print(np.zeros((2, 2)))
print ""

print(np.ones((3,4)))
print ""

print(np.eye(5))
print ""


[5 6 7 8]

[[1 2]
 [3 4]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]]

[ 1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.  ]

[[ 0.  0.]
 [ 0.  0.]]

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]



In [14]:
# element wise operation between 2 arrays 
print('Element wise operation result:')
print(a + b)
print(a * b)
print(a ** b)
print(3 * a)
print(a[a > 3])
print()

# bit wise operation
print('Bit wise wise operation result:')
print(a | b)
print(a & b)
print(a ^ b)

Element wise operation result:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
[[  1   2   3   4]
 [  1   4   9  16]
 [  1   8  27  64]
 [  1  16  81 256]]
[ 3  6  9 12]
[4]
()
Bit wise wise operation result:
[[1 3 3 5]
 [3 2 3 6]
 [3 3 3 7]
 [5 6 7 4]]
[[1 0 1 0]
 [0 2 2 0]
 [1 2 3 0]
 [0 0 0 4]]
[[0 3 2 5]
 [3 0 1 6]
 [2 1 0 7]
 [5 6 7 0]]


In [15]:
# shallow copy and deep copy 浅复制和深复制
# No copy
c = a;
a[0] = 100
print('No copy:')
print(a)
print(c)
print()

c = a.view()
print('View:')
print(c is a)
print(c.base is a)
c.shape = 2, 2
print(c.shape)
print(a.shape)
print()

# deep copy
c = a.copy();
a[0] = 1000
print('Deep copy:')
print(a)
print(c);




No copy:
[100   2   3   4]
[100   2   3   4]
()
View:
False
True
(2, 2)
(4,)
()
Deep copy:
[1000    2    3    4]
[100   2   3   4]


In [16]:
# segementation 切片
a = np.arange(10)
a.shape = (10, 1)
a = np.dot(a, a.transpose()) # a*aT
print(a)
print()
print(a[3:5, 3:5])
print()
print(a[1])



[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]
()
[[ 9 12]
 [12 16]]
()
[0 1 2 3 4 5 6 7 8 9]


In [17]:
b = a[3:7, 3:7]
b[:] = 11
print(a)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6 11 11 11 11 21 24 27]
 [ 0  4  8 11 11 11 11 28 32 36]
 [ 0  5 10 11 11 11 11 35 40 45]
 [ 0  6 12 11 11 11 11 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]


In [18]:
# Algebra
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print()

print(a.transpose()) # or a.T
print()

from numpy.linalg import inv
print(inv(a))
print()

print(np.trace(a))
print()

print(np.dot(a, b))



[[1 2]
 [3 4]]
()
[[1 3]
 [2 4]]
()
[[-2.   1. ]
 [ 1.5 -0.5]]
()
5
()
[[19 22]
 [43 50]]


In [19]:
# 维度退化
# 1d
print(a[1, :])
print(a[1, :].shape)
print(a[:,1]) # column vector with 2 dimension? No.

[3 4]
(2,)
[2 4]


# 6. Pandas

### series:
### dataframe:

In [20]:
import numpy as np
import pandas as pd
# series, corresponding to python list 
studentsSeries = pd.Series(['Lily', 'Lucy', 'Polly', np.nan, 'Uncle', 'Tom'])
print(studentsSeries)

0     Lily
1     Lucy
2    Polly
3      NaN
4    Uncle
5      Tom
dtype: object


In [21]:
# dataframe
index = ['Lily', 'Lucy', 'Polly', 'LiLei', 'Uncle', 'Tom']
studentDataFrame = pd.DataFrame({
        'Grade': np.array([1, 1, 2, 4, 3, 2], dtype = 'int32'),
        'Level': pd.Categorical(['Junior', 'Junior', 'Junior', 'Senior', 'Senior', 'Junior']),
        'TestResult': [99, 98, 97, 96, 95, 94]},
        index = index,
    )

print(studentDataFrame)
print(studentDataFrame.info())

       Grade   Level  TestResult
Lily       1  Junior          99
Lucy       1  Junior          98
Polly      2  Junior          97
LiLei      4  Senior          96
Uncle      3  Senior          95
Tom        2  Junior          94
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Lily to Tom
Data columns (total 3 columns):
Grade         6 non-null int32
Level         6 non-null category
TestResult    6 non-null int64
dtypes: category(1), int32(1), int64(1)
memory usage: 142.0+ bytes
None


In [22]:
# index
print(studentDataFrame['Grade']) # syntax-wise, similar to dictionary

Lily     1
Lucy     1
Polly    2
LiLei    4
Uncle    3
Tom      2
Name: Grade, dtype: int32


In [23]:
# segmentation切片
# 直接使用[]进行选择，只能选择一行或者一列
print(studentDataFrame[0:3])

print(studentDataFrame['Lily':'LiLei'])

       Grade   Level  TestResult
Lily       1  Junior          99
Lucy       1  Junior          98
Polly      2  Junior          97
       Grade   Level  TestResult
Lily       1  Junior          99
Lucy       1  Junior          98
Polly      2  Junior          97
LiLei      4  Senior          96


In [24]:
studentDataFrame['Grade']

studentDataFrame[0:1]['Grade'] = 10
studentDataFrame[0:1]

/Users/Ke/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()


Grade   Level  TestResult
Lily      1  Junior          99

In [25]:
print(studentDataFrame.loc['Lily'])
print ""
print(studentDataFrame.loc[:,'Grade']) # similar to numpy 2-d array
studentDataFrame.loc['Lily','Grade'] = 10 # now we can change the grade for Lily

Grade              1
Level         Junior
TestResult        99
Name: Lily, dtype: object

Lily     1
Lucy     1
Polly    2
LiLei    4
Uncle    3
Tom      2
Name: Grade, dtype: int32


In [26]:
print(studentDataFrame[['Grade', 'Level']])

       Grade   Level
Lily      10  Junior
Lucy       1  Junior
Polly      2  Junior
LiLei      4  Senior
Uncle      3  Senior
Tom        2  Junior


In [27]:
# tag selection: loc 标签选择
print(studentDataFrame.loc[:, ['Grade', 'Level']])

print(studentDataFrame.loc[['Lily', 'Lucy'], ['Grade', 'Level']])

       Grade   Level
Lily      10  Junior
Lucy       1  Junior
Polly      2  Junior
LiLei      4  Senior
Uncle      3  Senior
Tom        2  Junior
      Grade   Level
Lily     10  Junior
Lucy      1  Junior


In [28]:
# position selection: iloc 位置选择, i is for index
print(studentDataFrame.iloc[0: 3, 0: 3])

       Grade   Level  TestResult
Lily      10  Junior          99
Lucy       1  Junior          98
Polly      2  Junior          97


In [29]:
# condition selection: 条件选择
print(studentDataFrame[studentDataFrame['Grade'] > 1])

       Grade   Level  TestResult
Lily      10  Junior          99
Polly      2  Junior          97
LiLei      4  Senior          96
Uncle      3  Senior          95
Tom        2  Junior          94


In [30]:
# add one column: 增加一列
Gender = ['Female', 'Female', 'Female', 'Female', 'Female', 'Female']
studentDataFrame['Gender'] = Gender
print(studentDataFrame)

       Grade   Level  TestResult  Gender
Lily      10  Junior          99  Female
Lucy       1  Junior          98  Female
Polly      2  Junior          97  Female
LiLei      4  Senior          96  Female
Uncle      3  Senior          95  Female
Tom        2  Junior          94  Female


In [31]:
# observations
studentDataFrame.head(2)

Grade   Level  TestResult  Gender
Lily     10  Junior          99  Female
Lucy      1  Junior          98  Female

In [32]:
studentDataFrame.tail(2)

Grade   Level  TestResult  Gender
Uncle      3  Senior          95  Female
Tom        2  Junior          94  Female

In [33]:
# sort()
studentDataFrame.sort_values(by = 'TestResult') # return a sorted copy

Grade   Level  TestResult  Gender
Tom        2  Junior          94  Female
Uncle      3  Senior          95  Female
LiLei      4  Senior          96  Female
Polly      2  Junior          97  Female
Lucy       1  Junior          98  Female
Lily      10  Junior          99  Female

In [34]:
studentDataFrame

Grade   Level  TestResult  Gender
Lily      10  Junior          99  Female
Lucy       1  Junior          98  Female
Polly      2  Junior          97  Female
LiLei      4  Senior          96  Female
Uncle      3  Senior          95  Female
Tom        2  Junior          94  Female

In [ ]:
# please review SVM and/or dot product, what is vector, variance of mean.